# File: .github/workflows/aws-cred-test.yml
name: AWS Credentials Test

on:
  workflow_dispatch:  # This allows you to run the workflow manually from the Actions tab

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Test AWS CLI
      run: |
        aws sts get-caller-identity
        aws s3 ls  # This will list S3 buckets, adjust if needed

    - name: Echo Redacted Secrets
      run: |
        echo "Access Key ID: ${AWS_ACCESS_KEY_ID:0:5}..."
        echo "Secret Access Key: ${AWS_SECRET_ACCESS_KEY:0:5}..."
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
